# Generated by Django 5.1.7 on 2025-04-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='behavioral_weight',
            field=models.IntegerField(default=33),
        ),
        migrations.AddField(
            model_name='prompt',
            name='company_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.company'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='cultural_fit_weight',
            field=models.IntegerField(default=34),
        ),
        migrations.AddField(
            model_name='prompt',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='prompt',
            name='performance_weight',
            field=models.IntegerField(default=33),
        ),
        migrations.AddField(
            model_name='prompt',
            name='question_types',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prompt',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='prompt',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
    ]
