# Generated by Django 5.1.7 on 2025-04-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('company_size', models.CharField(choices=[('1-5', '1-5 employees'), ('6-10', '6-10 employees'), ('11-50', '11-50 employees'), ('51-100', '51-100 employees'), ('100+', 'More than 100 employees')], default='1-5', max_length=10)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('company_structure', models.CharField(choices=[('startup', 'Startup'), ('small_business', 'Small Business'), ('enterprise', 'Enterprise'), ('nonprofit', 'Nonprofit')], default='startup', max_length=20)),
                ('work_environment', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('office_based', 'Office Based')], default='remote', max_length=20)),
                ('communication_style', models.CharField(choices=[('async_first', 'Async-first'), ('real_time', 'Real-time'), ('hybrid', 'Hybrid')], default='async_first', max_length=20)),
                ('team_structure_overview', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='users.user')),
            ],
        ),
    ]
